openapi: 3.0.1
info:
  title: E-Commerce App API
  version: 1.0.0
  description: A fully-functioning e-commerce application REST API
paths:
  /products:
    get:
      operationId: getProducts
      summary: Get all Products
      responses:
        '200':
          $ref: '#/components/responses/productsSuccess'
      tags:
        - Products
    post:
      operationId: addProduct
      summary: Add a new Product
      requestBody:
        $ref: '#/components/requestBodies/Product'
      responses:
        '201':
          $ref: '#/components/responses/productSuccess'
      tags:
        - Products
    delete:
      operationId: deleteAllProducts
      summary: Delete all Products
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - Products
  /products/{productId}:
    get:
      operationId: getProductById
      summary: Get a Product by Product ID
      parameters:
      - $ref: '#/components/parameters/productId'
      responses:
        '200':
          $ref: '#/components/responses/productSuccess'
      tags:
        - Products
    put:
      operationId: updateProductById
      summary: Update a Product by Product ID
      parameters:
      - $ref: '#/components/parameters/productId'
      requestBody:
        $ref: '#/components/requestBodies/Product'
      responses:
        '200':
          $ref: '#/components/responses/productSuccess'
      tags:
        - Products
    delete:
      operationId: deleteProductById
      summary: Delete a Product by Product ID
      parameters:
      - $ref: '#/components/parameters/productId'
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - Products
  /users:
    get:
      operationId: getUsers
      summary: Get all Users
      responses:
        '200':
          $ref: '#/components/responses/usersSuccess'
      tags:
        - Users
    post:
      operationId: addUser
      summary: Add a new User
      requestBody:
        $ref: '#/components/requestBodies/NewUser'
      responses:
        '201':
          $ref: '#/components/responses/userSuccess'
      tags:
        - Users
    delete:
      operationId: deleteAllUsers
      summary: Delete all Users
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - Users
  /users/{userId}:
    get:
      operationId: getUserById
      summary: Get a User by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/userSuccess'
      tags:
        - Users
    put:
      operationId: updateUserById
      summary: Update a User by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '200':
          $ref: '#/components/responses/userSuccess'
      tags:
        - Users
    delete:
      operationId: deleteUserById
      summary: Delete a User by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - Users
  /users/{userId}/cart-items:
    get:
      operationId: getCartItemsByUser
      summary: Get all Cart Items by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/cartItemsSuccess'
      tags:
        - User - Shopping Cart
    post:
      operationId: addCartItemByUser
      summary: Add a new Cart Item by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '201':
          $ref: '#/components/responses/cartItemSuccess'
      tags:
        - User - Shopping Cart
    delete:
      operationId: deleteAllCartItemsByUser
      summary: Delete all Cart Items by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - User - Shopping Cart
  /users/{userId}/cart-items/{productId}:
    get:
      operationId: getCartItemByUserAndProduct
      summary: Get a Cart Item by User ID and Product ID
      parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/productId'
      responses:
        '200':
          $ref: '#/components/responses/cartItemSuccess'
      tags:
        - User - Shopping Cart
    put:
      operationId: updateCartItemByUserAndProduct
      summary: Update a Cart Item by User ID and Product ID
      parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/productId'
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '200':
          $ref: '#/components/responses/cartItemSuccess'
      tags:
        - User - Shopping Cart
    delete:
      operationId: deleteCartItemByUserAndProduct
      summary: Delete a Cart Item by User ID and Product ID
      parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/productId'
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - User - Shopping Cart
  /users/{userId}/orders:
    get:
      operationId: getOrdersByUser
      summary: Get all Orders by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/ordersSuccess'
      tags:
        - User - Orders
    delete:
      operationId: deleteAllOrdersByUser for User ID
      summary: Delete all Orders by User ID
      parameters:
      - $ref: '#/components/parameters/userId'
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - User - Orders
  /orders:
    get:
      operationId: getOrders
      summary: Get all Orders
      responses:
        '200':
          $ref: '#/components/responses/ordersSuccess'
      tags:
        - Orders
    post:
      operationId: addOrder
      summary: Add a new Order
      requestBody:
        $ref: '#/components/requestBodies/Order'
      responses:
        '201':
          $ref: '#/components/responses/orderSuccess'
      tags:
        - Orders
    delete:
      operationId: deleteAllOrdersByUser
      summary: Delete all Orders
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - Orders
  /orders/{orderId}:
    get:
      operationId: getOrderById
      summary: Get an Order by ID
      parameters:
      - $ref: '#/components/parameters/orderId'
      responses:
        '200':
          $ref: '#/components/responses/orderSuccess'
      tags:
        - Orders
    put:
      operationId: updateOrderById
      summary: Update an Order by ID
      parameters:
      - $ref: '#/components/parameters/orderId'
      requestBody:
        $ref: '#/components/requestBodies/Order'
      responses:
        '200':
          $ref: '#/components/responses/orderSuccess'
      tags:
        - Orders
    delete:
      operationId: deleteOrderById
      summary: Delete an Order by ID
      parameters:
      - $ref: '#/components/parameters/orderId'
      responses:
        '204':
          $ref: '#/components/responses/deleteSuccess'
      tags:
        - Orders
  /orders/{orderId}/status:
    get:
      operationId: getOrderStatusByID
      summary: Get an Order Status by ID
      parameters:
      - $ref: '#/components/parameters/orderId'
      responses:
        '200':
          $ref: '#/components/responses/orderStatusSuccess'
      tags:
        - Orders
    put:
      operationId: updateOrderStatusById
      summary: Update an Order Status by ID
      parameters:
      - $ref: '#/components/parameters/orderId'
      requestBody:
        $ref: '#/components/requestBodies/OrderStatus'
      responses:
        '200':
          $ref: '#/components/responses/orderStatusSuccess'
      tags:
        - Orders
  /auth/register:
    post:
      operationId: AuthRegisterUser
      summary: Register a new User
      requestBody:
        $ref: '#/components/requestBodies/NewUser'
      responses:
        '201':
          $ref: '#/components/responses/userSuccess'
      tags:
        - Authentication
  /auth/login:
    post:
      operationId: AuthLogin
      summary: Authenticate a User and start a User session
      requestBody:
        $ref: '#/components/requestBodies/UserLogin'
      responses:
        '200':
          $ref: '#/components/responses/userSuccess'
      tags:
        - Authentication
  /auth/logout:
    post:
      operationId: AuthLogout
      summary: End User session
      responses:
        '204':
          $ref: '#/components/responses/logoutSuccess'
      tags:
        - Authentication
components:
  schemas:
    OrderStatus:
      type: string
      enum:
        - created
        - accepted
        - paid
        - posted
        - recieved
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        name:
          type: string
        description:
          type: string
        unit_price:
          type: number
          multipleOf: 0.01
          minimum: 0
        stock:
          type: integer
          format: int32
          minimum: 0
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    NewUser:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        name:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
        password:
          type: string
    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        name:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    CartItem:
      type: object
      properties:
        userId:
          type: integer
          format: int32
          minimum: 0
        productId:
          type: integer
          format: int32
          minimum: 0
        amount:
          type: integer
          format: int32
          minimum: 0
    CartItems:
      type: array
      items:
        $ref: '#/components/schemas/CartItem'
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        userId:
          type: integer
          format: int32
          minimum: 0
        created:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/OrderStatus'
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'
  parameters:
    userId:
      name: userId
      in: path
      description: unique id for a User
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
    productId:
      name: productId
      in: path
      description: unique id for a Product
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
    orderId:
      name: orderId
      in: path
      description: unique id for an Order
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
  responses:
    userSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: Success
    usersSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Users'
      description: Success
    cartItemSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CartItem'
      description: Success
    cartItemsSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CartItems'
      description: Success
    productSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
      description: Success
    productsSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Products'
      description: Success
    orderSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
      description: Success
    ordersSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Orders'
      description: Success
    orderStatusSuccess:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderStatus'
      description: Success
    deleteSuccess:
      content:
        application/json:
          schema:
            type: string
      description: Delete operation was successful
    logoutSuccess:
      content:
        application/json:
          schema:
            type: string
      description: Logout operation was successful
    genericStringResponse:
      content:
        application/json:
          schema:
            type: string
      description: A string response
    emptyResponse:
      description: An empty response body
  requestBodies:
    Product:
      description: A Product object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
      required: true
    NewUser:
      description: A Product object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewUser'
      required: true
    UserLogin:
      description: A Product object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserLogin'
      required: true
    User:
      description: A User object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      required: true
    CartItems:
      description: A Cart Items object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CartItems'
      required: true
    Order:
      description: An order object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
      required: true
    OrderStatus:
      description: An Order Status
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderStatus'
      required: true
  