openapi: 3.0.1
info:
  title: E-Commerce App API
  version: 1.0.0
  description: A fully-functioning e-commerce application REST API
paths:
  /products:
    get:
      operationId: getProducts
      summary: Gets all Products
    post:
      operationId: addProduct
      summary: Adds a new Product
    delete:
      operationId: deleteAllProducts
      summary: Delete all Products
  /products/{product_id}:
    get:
      operationId: getProductById
      summary: Gets a Product by Product ID
    put:
      operationId: updateProductById
      summary: Updates a Product by Product ID
    delete:
      operationId: deleteProductById
      summary: Deletes a Product by Product ID
  /users:
    get:
      operationId: getUsers
      summary: Gets all Users
    post:
      operationId: addUser
      summary: Adds a new User
    delete:
      operationId: deleteAllUsers
      summary: Delete all Users
  /users/{user_id}:
    get:
      operationId: getUserById
      summary: Gets a User by User ID
    put:
      operationId: updateUserById
      summary: Updates a User by User ID
    delete:
      operationId: deleteUserById
      summary: Deletes a User by User ID
  /users/{user_id}/cart_items:
    get:
      operationId: getCartItemsByUser
      summary: Gets all Cart Items by User ID
    post:
      operationId: addCartItemByUser
      summary: Adds a new Cart Item by User ID
    delete:
      operationId: deleteAllCartItemsByUser
      summary: Delete all Cart Items by User ID
  /users/{user_id}/cart_items/{product_id}:
    get:
      operationId: getCartItemByUserAndProduct
      summary: Gets a Cart Item by User ID and Product ID
    put:
      operationId: updateCartItemByUserAndProduct
      summary: Updates a Cart Item by User ID and Product ID
    delete:
      operationId: deleteCartItemByUserAndProduct
      summary: Deletes a Cart Item by User ID and Product ID
  /users/{user_id}/orders:
    get:
      operationId: getOrdersByUser
      summary: Gets all Orders by User ID
    post:
      operationId: addOrderByUser
      summary: Adds a new Order by User ID
    delete:
      operationId: deleteAllOrdersByUser for User ID
      summary: Delete all Orders by User ID
  /orders:
    get:
      operationId: getOrders
      summary: Gets all Orders
    post:
      operationId: addOrder
      summary: Adds a new Order
    delete:
      operationId: deleteAllOrdersByUser
      summary: Delete all Orders
  /orders/{order_id}/:
    get:
      operationId: getOrderById
      summary: Gets an Order by ID
    put:
      operationId: updateOrderById
      summary: Updates an Order by ID
    delete:
      operationId: deleteOrderById
      summary: Deletes an Order by ID
  /orders/{order_id}/status:
    get:
      operationId: getOrderStatusByID
      summary: Gets an Order Status by ID
    put:
      operationId: updateOrderStatusById
      summary: Updates an Order Status by ID
  /auth/register:
    post:
      operationId: AuthRegisterUser
      summary: Registers a new User
  /auth/login:
    post:
      operationId: AuthLogin
      summary: Authenticates a user and starts a session
  /auth/logout:
    post:
      operationId: AuthLogout
      summary: Registers a new User
components:
  schemas:
    OrderStatus:
      type: string
      enum:
        - created
        - accepted
        - paid
        - posted
        - recieved
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        name:
          type: string
        description:
          type: string
        unit_price:
          type: number
          multipleOf: 0.01
          minimum: 0
        stock:
          type: integer
          format: int32
          minimum: 0
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        name:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
        is_admin:
          type: boolean
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    CartItem:
      type: object
      properties:
        userId:
          type: integer
          format: int32
          minimum: 0
        productId:
          type: integer
          format: int32
          minimum: 0
        amount:
          type: integer
          format: int32
          minimum: 0
    CartItems:
      type: array
      items:
        $ref: '#/components/schemas/CartItem'
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
        userId:
          type: integer
          format: int32
          minimum: 0
        created:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/OrderStatus'
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'